In [1]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df_1 = df.head()
df_2 = df.tail(1)

In [5]:
nor_minmax = MinMaxScaler().fit(df_1.iloc[:, :-1])
nor_minmax

MinMaxScaler()

In [6]:
print(nor_minmax.data_max_, nor_minmax.data_min_)

[5.1 3.6 1.5 0.2] [4.6 3.  1.3 0.2]


In [7]:
type(nor_minmax.data_max_)

numpy.ndarray

In [8]:
pd.DataFrame([nor_minmax.data_max_, nor_minmax.data_min_], columns = df.columns[0:4])

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           5.1          3.6           1.5          0.2
1           4.6          3.0           1.3          0.2

In [9]:
nor_minmax.transform(df_1.iloc[:, :-1])

array([[1.        , 0.83333333, 0.5       , 0.        ],
       [0.6       , 0.        , 0.5       , 0.        ],
       [0.2       , 0.33333333, 0.        , 0.        ],
       [0.        , 0.16666667, 1.        , 0.        ],
       [0.8       , 1.        , 0.5       , 0.        ]])

In [10]:
nor_minmax.transform(df_2.iloc[:, :-1])

array([[ 2.6,  0. , 19. ,  1.6]])

In [12]:
df_minmax = pd.DataFrame(nor_minmax.transform(df_1.iloc[:, :-1]), columns=df_1.columns[:-1])

In [13]:
df_minmax

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           1.0     0.833333           0.5          0.0
1           0.6     0.000000           0.5          0.0
2           0.2     0.333333           0.0          0.0
3           0.0     0.166667           1.0          0.0
4           0.8     1.000000           0.5          0.0

In [15]:
model = KMeans(n_clusters=3, random_state=123).fit(df.iloc[:, :-1])
model

KMeans(n_clusters=3, random_state=123)

In [16]:
model.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2], dtype=int32)

In [17]:
model.cluster_centers_

array([[6.85      , 3.07368421, 5.74210526, 2.07105263],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.9016129 , 2.7483871 , 4.39354839, 1.43387097]])

In [18]:
pd.DataFrame(model.cluster_centers_, columns=df.columns[:-1])

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0      6.850000     3.073684      5.742105     2.071053
1      5.006000     3.428000      1.462000     0.246000
2      5.901613     2.748387      4.393548     1.433871

# Q1

In [20]:
import pandas as pd
from sklearn.cluster import KMeans

In [21]:
df_q1 = pd.read_csv('diabetes.csv')
df_q1.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1
3            1       89             66             23       94  28.1                     0.167   21        0
4            0      137             40             35      168  43.1                     2.288   33        1

In [24]:
df_q1 = df_q1[df_q1['BMI'] != 0]

In [28]:
kmean = KMeans(n_clusters=4, random_state=123).fit(df_q1)

In [29]:
kmean.labels_

array([0, 0, 0, 2, 3, 0, 2, 0, 1, 0, 0, 0, 1, 3, 0, 3, 0, 2, 2, 3, 0, 0,
       0, 2, 2, 0, 2, 2, 0, 0, 3, 2, 0, 0, 3, 0, 0, 0, 3, 2, 0, 0, 3, 0,
       0, 0, 0, 0, 2, 0, 0, 3, 3, 0, 3, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0,
       2, 2, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 3,
       2, 0, 2, 3, 0, 2, 2, 3, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 1, 0, 0,
       3, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 0, 3, 0, 3, 0, 0, 2,
       2, 2, 0, 3, 0, 0, 2, 0, 3, 0, 2, 0, 0, 3, 0, 3, 1, 0, 0, 2, 2, 2,
       2, 0, 2, 3, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 0, 0, 0,
       2, 0, 0, 0, 0, 1, 2, 2, 3, 0, 2, 0, 0, 0, 3, 0, 0, 2, 3, 0, 0, 0,
       0, 3, 0, 3, 0, 2, 0, 0, 0, 0, 2, 3, 3, 2, 2, 0, 0, 1, 0, 0, 3, 2,
       0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 3, 3, 0, 0,
       1, 1, 0, 0, 0, 2, 0, 3, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 3, 0, 2, 2, 0, 0, 2, 1, 3, 0, 2, 0,
       2, 3, 3, 0, 2, 3, 3, 3, 0, 0, 2, 0, 0, 0, 2,

In [32]:
df_q1['label'] = kmean.labels_

In [33]:
df_q1.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome  label
0            6      148             72             35        0  33.6                     0.627   50        1      0
1            1       85             66             29        0  26.6                     0.351   31        0      0
2            8      183             64              0        0  23.3                     0.672   32        1      0
3            1       89             66             23       94  28.1                     0.167   21        0      2
4            0      137             40             35      168  43.1                     2.288   33        1      3

In [39]:
df_q1['label'].value_counts()

label
0    397
2    219
3    117
1     24
Name: count, dtype: int64

In [36]:
df_q1[df_q1['label'] == 0]['Insulin'].mean()

np.float64(2.957178841309824)

# Q2

In [41]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

In [42]:
df_q2 = pd.read_csv('diabetes.csv')
df_q2.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1
3            1       89             66             23       94  28.1                     0.167   21        0
4            0      137             40             35      168  43.1                     2.288   33        1

In [43]:
df_q2 = df_q2[df_q2['BMI'] != 0]

In [48]:
df_q2_nor = MinMaxScaler().fit(df_q2).transform(df_q2)

In [50]:
df_q2_nor

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.23441503, 0.48333333,
        1.        ],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.11656704, 0.16666667,
        0.        ],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.25362938, 0.18333333,
        1.        ],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.07130658, 0.15      ,
        0.        ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.11571307, 0.43333333,
        1.        ],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.10119556, 0.03333333,
        0.        ]], shape=(757, 9))

In [51]:
df_q2_nor = pd.DataFrame(df_q2_nor, columns=df_q2.columns)

In [52]:
df_q2_nor.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  DiabetesPedigreeFunction       Age  Outcome
0     0.352941  0.743719       0.590164       0.353535  0.000000  0.314928                  0.234415  0.483333      1.0
1     0.058824  0.427136       0.540984       0.292929  0.000000  0.171779                  0.116567  0.166667      0.0
2     0.470588  0.919598       0.524590       0.000000  0.000000  0.104294                  0.253629  0.183333      1.0
3     0.058824  0.447236       0.540984       0.232323  0.111111  0.202454                  0.038002  0.000000      0.0
4     0.000000  0.688442       0.327869       0.353535  0.198582  0.509202                  0.943638  0.200000      1.0

In [54]:
df_q2_kmeans = KMeans(n_clusters=4, random_state=123).fit(df_q2_nor)

In [55]:
df_q2_kmeans.labels_

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 3, 1, 1, 1, 1, 1, 2, 1, 2, 3, 1,
       1, 1, 1, 1, 0, 3, 3, 3, 1, 0, 0, 3, 2, 3, 1, 1, 1, 2, 3, 3, 1, 3,
       1, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 2, 2, 2, 1, 0, 2, 1, 0, 1, 3, 0,
       2, 1, 2, 1, 2, 0, 0, 3, 2, 1, 0, 0, 3, 0, 1, 2, 3, 2, 1, 0, 0, 2,
       3, 1, 0, 3, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 2, 0, 1, 1, 1, 2, 0,
       1, 1, 1, 0, 0, 0, 1, 2, 2, 3, 1, 1, 2, 2, 1, 1, 1, 1, 1, 3, 0, 2,
       0, 0, 0, 2, 3, 3, 0, 1, 2, 3, 2, 3, 0, 2, 0, 1, 2, 1, 1, 0, 0, 0,
       1, 2, 3, 2, 0, 1, 1, 2, 0, 0, 0, 1, 1, 0, 2, 0, 1, 3, 1, 3, 1, 0,
       2, 0, 0, 3, 1, 1, 1, 1, 1, 0, 3, 1, 1, 3, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 3, 0, 1, 1, 2, 1, 0, 2, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 3, 0,
       2, 0, 1, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 2, 1, 1, 2, 1, 3,
       2, 2, 0, 3, 0, 0, 2, 1, 1, 2, 0, 2, 1, 2, 1, 2, 3, 1, 3, 1, 2, 0,
       1, 1, 0, 0, 2, 3, 2, 1, 0, 3, 0, 1, 3, 3, 1, 1, 3, 2, 1, 0, 2, 2,
       1, 1, 1, 3, 2, 1, 2, 1, 3, 1, 1, 2, 1, 0, 2,

In [56]:
df_q2['label'] = df_q2_kmeans.labels_

In [57]:
df_q2['label'].value_counts()

label
1    266
0    214
2    162
3    115
Name: count, dtype: int64

In [59]:
df_q2[df_q2['label'] == 1]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome  label
0              6      148             72             35        0  33.6                     0.627   50        1      1
2              8      183             64              0        0  23.3                     0.672   32        1      1
4              0      137             40             35      168  43.1                     2.288   33        1      1
6              3       78             50             32       88  31.0                     0.248   26        1      1
8              2      197             70             45      543  30.5                     0.158   53        1      1
..           ...      ...            ...            ...      ...   ...                       ...  ...      ...    ...
755            1      128             88             39      110  36.5                     1.057   37        1      1
757            0      123             72              0        0  36.3                     0.258   52        1      1
759            6      190             92              0        0  35.5                     0.278   66        1      1
761            9      170             74             31        0  44.0                     0.403   43        1      1
766            1      126             60              0        0  30.1                     0.349   47        1      1

[266 rows x 10 columns]

In [60]:
df_q2[df_q2['label'] == 1]['Age'].mean().round(0)

np.float64(37.0)

# Q3

In [61]:
import pandas as panda
from sklearn.cluster import KMeans

In [75]:
df_q3 = pd.read_csv('diabetes.csv')
df_q3.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1
3            1       89             66             23       94  28.1                     0.167   21        0
4            0      137             40             35      168  43.1                     2.288   33        1

In [76]:
df_q3 = df_q3[df_q3['BMI'] != 0].reset_index(drop=True)

In [77]:
df_q3_centres = pd.DataFrame(KMeans(n_clusters=3, random_state=123).fit(df_q3).cluster_centers_, columns=df_q3.columns)

In [78]:
df_q3['label'] = KMeans(n_clusters=3, random_state=123).fit(df_q3).labels_

In [79]:
df_q3.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome  label
0            6      148             72             35        0  33.6                     0.627   50        1      0
1            1       85             66             29        0  26.6                     0.351   31        0      0
2            8      183             64              0        0  23.3                     0.672   32        1      0
3            1       89             66             23       94  28.1                     0.167   21        0      2
4            0      137             40             35      168  43.1                     2.288   33        1      2

In [80]:
df_q3_centres

Pregnancies     Glucose  BloodPressure  SkinThickness  ...        BMI  DiabetesPedigreeFunction        Age   Outcome
0     3.975258  114.237113      68.647423      15.259794  ...  31.440619                  0.434579  33.808247  0.301031
1     4.026316  158.447368      72.000000      32.263158  ...  35.107895                  0.569211  34.763158  0.578947
2     3.542735  129.376068      71.478632      30.337607  ...  34.134615                  0.535188  31.948718  0.418803

[3 rows x 9 columns]

In [87]:
for i in range(3):
    for j in range(i, 3):
        if i == j:
            continue
        print(i, j, ((df_q3_centres.iloc[i,] - df_q3_centres.iloc[j,]) ** 2).sum() ** 0.5)

0 1 429.24419310888464
0 2 146.33847909815492
1 2 283.405999774738
