# Q1

In [73]:
import pandas as pd

In [74]:
df_1 = pd.read_csv('lv2-2305-2.csv')

In [75]:
df_1.head()

REG_NO  GRE  TOEFL UNIV_RATING  SOP  LOR  CGPA  RESEARCH     ADMIT
0       1  337    118           B  4.5  4.5  9.65         1  Admitted
1       2  324    107           B  4.0  4.5  8.87         1  Admitted
2       3  316    104           C  3.0  3.5  8.00         1    Denied
3       4  322    110           C  3.5  2.5  8.67         1  Admitted
4       5  314    103           D  2.0  3.0  8.21         0    Denied

In [76]:
df_1.shape

(400, 9)

### 1-1

In [77]:
df_1_adm = df_1[df_1['ADMIT'] == 'Admitted']

In [78]:
df_1_adm.shape

(180, 9)

In [79]:
df_1_den = df_1[df_1['ADMIT'] == 'Denied']
df_1_den.shape

(220, 9)

### 1-2

In [80]:
df_1_adm['GRE'].rank(method='min', ascending=False)

0       16.0
1       97.0
3      120.0
5       51.0
6      131.0
       ...  
394     57.0
395     97.0
396     89.0
397     51.0
399     33.0
Name: GRE, Length: 180, dtype: float64

In [81]:
targets = ['GRE', 'TOEFL', 'CGPA']

for target in targets:
    data = df_1_adm.loc[:, target].rank(method='min', ascending=False).copy()
    df_1_adm.loc[:, [target + '_R']] = data
    data = df_1_den.loc[:, target].rank(method='min', ascending=False).copy()
    df_1_den.loc[:, [target + '_R']] = data

In [82]:
df_1_adm

REG_NO  GRE  TOEFL UNIV_RATING  SOP  LOR  CGPA  RESEARCH     ADMIT  \
0         1  337    118           B  4.5  4.5  9.65         1  Admitted   
1         2  324    107           B  4.0  4.5  8.87         1  Admitted   
3         4  322    110           C  3.5  2.5  8.67         1  Admitted   
5         6  330    115           A  4.5  3.0  9.34         1  Admitted   
6         7  321    109           C  3.0  4.0  8.20         1  Admitted   
..      ...  ...    ...         ...  ...  ...   ...       ...       ...   
394     395  329    111           B  4.5  4.0  9.23         1  Admitted   
395     396  324    110           C  3.5  3.5  9.04         1  Admitted   
396     397  325     67           C  3.0  3.5  9.11         1  Admitted   
397     398  330    116           B  5.0  4.5  9.45         1  Admitted   
399     400  333    117           B  5.0  4.0  9.66         1  Admitted   

     GRE_R  TOEFL_R  CGPA_R  
0     16.0     18.0    18.0  
1     97.0    153.0   126.0  
3    120.0    109.0   154.0  
5     51.0     45.0    47.0  
6    131.0    135.0   179.0  
..     ...      ...     ...  
394   57.0     94.0    58.0  
395   97.0    109.0   102.0  
396   89.0    179.0    85.0  
397   51.0     34.0    31.0  
399   33.0     27.0    15.0  

[180 rows x 12 columns]

In [83]:
df_1_den

REG_NO  GRE  TOEFL UNIV_RATING  SOP  LOR  CGPA  RESEARCH   ADMIT  GRE_R  \
2         3  316    104           C  3.0  3.5  8.00         1  Denied   50.0   
4         5  314    103           D  2.0  3.0  8.21         0  Denied   71.0   
7         8  308    101           D  3.0  4.0  7.90         0  Denied  125.0   
8         9  302    102           E  2.0  1.5  8.00         0  Denied  166.0   
9        10  323    108           C  3.5  3.0  8.60         0  Denied   15.0   
..      ...  ...    ...         ...  ...  ...   ...       ...     ...    ...   
387     388  307    105           D  2.0  3.5  8.10         0  Denied  134.0   
388     389  296     97           D  1.5  2.0  7.80         0  Denied  207.0   
390     391  314    102           D  2.0  2.5  8.24         0  Denied   71.0   
391     392  318    106           C  2.0  3.0  8.65         0  Denied   34.0   
398     399  312    103           C  3.5  4.0  8.78         0  Denied   88.0   

     TOEFL_R  CGPA_R  
2      102.0   155.0  
4      123.0   114.0  
7      150.0   168.0  
8      136.0   155.0  
9       31.0    39.0  
..       ...     ...  
387     77.0   136.0  
388    203.0   185.0  
390    136.0   107.0  
391     57.0    30.0  
398    123.0    13.0  

[220 rows x 12 columns]

### 1-3

In [84]:
from scipy.stats import spearmanr

In [85]:
spearmanr(df_1_adm['CGPA_R'], df_1_adm['GRE_R'])

SignificanceResult(statistic=np.float64(0.7770913247704572), pvalue=np.float64(1.2346594088259062e-37))

In [86]:
spearmanr(df_1_adm['CGPA_R'], df_1_adm['TOEFL_R'])

SignificanceResult(statistic=np.float64(0.7385953075966454), pvalue=np.float64(2.65633884835193e-32))

In [87]:
A = 0.7770913247704572
A_VAR = 'CGPA_R'

In [88]:
spearmanr(df_1_den['CGPA_R'], df_1_den['GRE_R'])

SignificanceResult(statistic=np.float64(0.5954030737434418), pvalue=np.float64(1.7069327747848276e-22))

In [89]:
spearmanr(df_1_den['CGPA_R'], df_1_den['TOEFL_R'])

SignificanceResult(statistic=np.float64(0.6167243066525749), pvalue=np.float64(1.918727502244697e-24))

In [90]:
B = 0.6167243066525749
B_VAR = 'TOEFL_R'

### Q1 Answer

In [91]:
round((A - B), 2)

0.16

# Q2

In [107]:
import pandas as pd

In [108]:
df_2 = pd.read_csv('lv2-2305-2.csv')

In [109]:
df_2.head()

REG_NO  GRE  TOEFL UNIV_RATING  SOP  LOR  CGPA  RESEARCH     ADMIT
0       1  337    118           B  4.5  4.5  9.65         1  Admitted
1       2  324    107           B  4.0  4.5  8.87         1  Admitted
2       3  316    104           C  3.0  3.5  8.00         1    Denied
3       4  322    110           C  3.5  2.5  8.67         1  Admitted
4       5  314    103           D  2.0  3.0  8.21         0    Denied

In [110]:
df_2.shape

(400, 9)

### 2-1

In [111]:
q1 = df_2['TOEFL'].quantile(0.25)

In [112]:
q3 = df_2['TOEFL'].quantile(0.75)

In [113]:
q1, q3

(np.float64(103.0), np.float64(112.0))

In [114]:
iqr = q3 - q1
iqr

np.float64(9.0)

In [115]:
df_2 = df_2[df_2['TOEFL'] >= (q1 - 1.5 * iqr)]

In [116]:
df_2 = df_2[df_2['TOEFL'] <= (q3 + 1.5 * iqr)]

In [117]:
df_2.shape

(396, 9)

### 2-2

In [118]:
df_2['ADMIT_S'] = (df_2['ADMIT'] == 'Admitted') + 0

In [119]:
df_2.head()

REG_NO  GRE  TOEFL UNIV_RATING  SOP  LOR  CGPA  RESEARCH     ADMIT  ADMIT_S
0       1  337    118           B  4.5  4.5  9.65         1  Admitted        1
1       2  324    107           B  4.0  4.5  8.87         1  Admitted        1
2       3  316    104           C  3.0  3.5  8.00         1    Denied        0
3       4  322    110           C  3.5  2.5  8.67         1  Admitted        1
4       5  314    103           D  2.0  3.0  8.21         0    Denied        0

### 2-3

In [124]:
from sklearn.linear_model import LogisticRegression

In [125]:
target_features = ['GRE', 'TOEFL', 'SOP', 'LOR', 'CGPA']

In [126]:
model = LogisticRegression(solver='newton-cg', C=100000, random_state=1234).fit(y=df_2['ADMIT_S'], X= df_2.loc[:, target_features])

### 2-4

In [127]:
pred = model.predict(df_2.loc[:, target_features])

In [128]:
pred

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [129]:
from sklearn.metrics import accuracy_score

### Q2 ANSWER

In [132]:
round(accuracy_score(y_true=df_2['ADMIT_S'], y_pred=pred) * 100,2)

87.63

# Q3

### 3-1

In [330]:
import pandas as pd

In [331]:
df_q3 = pd.read_csv('lv2-2305-2.csv')
df_q3.head()

REG_NO  GRE  TOEFL UNIV_RATING  SOP  LOR  CGPA  RESEARCH     ADMIT
0       1  337    118           B  4.5  4.5  9.65         1  Admitted
1       2  324    107           B  4.0  4.5  8.87         1  Admitted
2       3  316    104           C  3.0  3.5  8.00         1    Denied
3       4  322    110           C  3.5  2.5  8.67         1  Admitted
4       5  314    103           D  2.0  3.0  8.21         0    Denied

In [332]:
df_q3 = df_q3[df_q3['ADMIT'] == 'Denied']
df_q3.head()

REG_NO  GRE  TOEFL UNIV_RATING  SOP  LOR  CGPA  RESEARCH   ADMIT
2       3  316    104           C  3.0  3.5  8.00         1  Denied
4       5  314    103           D  2.0  3.0  8.21         0  Denied
7       8  308    101           D  3.0  4.0  7.90         0  Denied
8       9  302    102           E  2.0  1.5  8.00         0  Denied
9      10  323    108           C  3.5  3.0  8.60         0  Denied

### 3-2

In [333]:
dummies = pd.get_dummies(data=df_q3['UNIV_RATING'], drop_first=True, prefix='UR', dtype='int')
df_q3.loc[:, dummies.columns] = dummies.iloc[:,:]

In [334]:
df_q3.head()

REG_NO  GRE  TOEFL UNIV_RATING  SOP  LOR  CGPA  RESEARCH   ADMIT  UR_B  \
2       3  316    104           C  3.0  3.5  8.00         1  Denied     0   
4       5  314    103           D  2.0  3.0  8.21         0  Denied     0   
7       8  308    101           D  3.0  4.0  7.90         0  Denied     0   
8       9  302    102           E  2.0  1.5  8.00         0  Denied     0   
9      10  323    108           C  3.5  3.0  8.60         0  Denied     0   

   UR_C  UR_D  UR_E  
2     1     0     0  
4     0     1     0  
7     0     1     0  
8     0     0     1  
9     1     0     0

### 3-3

In [335]:
target_features = ['GRE', 'TOEFL', 'SOP', 'LOR', 'CGPA']

In [336]:
from sklearn.preprocessing import MinMaxScaler

In [337]:
df_q3.dtypes

REG_NO           int64
GRE              int64
TOEFL            int64
UNIV_RATING     object
SOP            float64
LOR            float64
CGPA           float64
RESEARCH         int64
ADMIT           object
UR_B             int64
UR_C             int64
UR_D             int64
UR_E             int64
dtype: object

In [338]:
df_q3['GRE'] = df_q3['GRE'].astype('float')
df_q3['TOEFL'] = df_q3['TOEFL'].astype('float')
df_q3.dtypes

REG_NO           int64
GRE            float64
TOEFL          float64
UNIV_RATING     object
SOP            float64
LOR            float64
CGPA           float64
RESEARCH         int64
ADMIT           object
UR_B             int64
UR_C             int64
UR_D             int64
UR_E             int64
dtype: object

In [339]:
for target in target_features:
    scaled = MinMaxScaler().fit_transform(X=df_q3.loc[:, [target]])
    df_q3.loc[:, [target]] = scaled

In [340]:
df_q3.head()

REG_NO       GRE     TOEFL UNIV_RATING    SOP    LOR      CGPA  RESEARCH  \
2       3  0.666667  0.825397           C  0.500  0.625  0.495868         1   
4       5  0.615385  0.809524           D  0.250  0.500  0.582645         0   
7       8  0.461538  0.777778           D  0.500  0.750  0.454545         0   
8       9  0.307692  0.793651           E  0.250  0.125  0.495868         0   
9      10  0.846154  0.888889           C  0.625  0.500  0.743802         0   

    ADMIT  UR_B  UR_C  UR_D  UR_E  
2  Denied     0     1     0     0  
4  Denied     0     0     1     0  
7  Denied     0     0     1     0  
8  Denied     0     0     0     1  
9  Denied     0     1     0     0

### 3-4

In [341]:
from sklearn.cluster import KMeans

In [342]:
target_features = ['GRE', 'TOEFL', 'SOP', 'LOR', 'CGPA', 'RESEARCH', 'UR_B', 'UR_C', 'UR_D', 'UR_E']

In [348]:
model_4 = KMeans(n_clusters=4, random_state=1234, n_init=50, max_iter=30).fit(X=df_q3.loc[:, target_features])
model_4.predict(X=df_q3.loc[:, target_features])

array([0, 1, 1, 3, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 3, 1, 3, 1, 1, 0, 1, 3,
       3, 1, 0, 1, 1, 1, 0, 2, 2, 2, 1, 3, 1, 1, 2, 1, 1, 2, 2, 2, 1, 0,
       2, 1, 0, 1, 1, 3, 0, 2, 1, 2, 0, 1, 2, 1, 1, 2, 3, 1, 0, 1, 1, 1,
       0, 0, 2, 2, 0, 0, 1, 0, 0, 2, 3, 1, 0, 3, 2, 3, 0, 2, 1, 2, 1, 1,
       3, 3, 3, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 0, 1,
       2, 1, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 2, 2, 0, 1, 1, 2, 3, 3, 1, 0,
       1, 2, 1, 0, 1, 1, 2, 1, 0, 2, 1, 0, 1, 1, 3, 3, 3, 1, 1, 1, 0, 1,
       1, 1, 3, 1, 1, 2, 1, 1, 1, 0, 1, 0, 2, 3, 2, 1, 1, 1, 3, 0, 1, 1,
       2, 2, 1, 1, 1, 0, 0, 2, 2, 1, 1, 3, 1, 3, 3, 2, 0, 0, 1, 2, 1, 1,
       1, 1, 1, 0, 3, 3, 3, 1, 1, 1, 1, 3, 3, 3, 0, 2, 1, 1, 1, 1, 2, 2],
      dtype=int32)

In [350]:
model_5 = KMeans(n_clusters=5, random_state=1234, n_init=50, max_iter=30).fit(X=df_q3.loc[:, target_features])
model_5.predict(X=df_q3.loc[:, target_features])

array([0, 3, 3, 1, 4, 0, 0, 0, 4, 4, 0, 4, 4, 0, 1, 2, 1, 3, 2, 0, 3, 1,
       1, 3, 0, 2, 2, 2, 0, 4, 4, 4, 3, 1, 3, 3, 4, 2, 2, 4, 1, 4, 2, 0,
       4, 2, 0, 3, 2, 1, 0, 4, 3, 4, 0, 2, 4, 3, 2, 4, 1, 3, 0, 3, 3, 3,
       0, 0, 4, 1, 0, 0, 3, 0, 0, 4, 1, 3, 0, 1, 4, 1, 0, 1, 2, 4, 3, 3,
       1, 1, 1, 4, 4, 4, 4, 2, 3, 2, 4, 4, 4, 3, 3, 3, 3, 3, 4, 4, 0, 2,
       4, 3, 3, 0, 3, 0, 4, 3, 3, 3, 3, 3, 4, 4, 0, 3, 3, 4, 1, 1, 3, 0,
       3, 4, 3, 0, 3, 2, 4, 2, 0, 4, 3, 0, 2, 3, 1, 1, 1, 3, 3, 3, 0, 3,
       3, 3, 1, 2, 3, 4, 3, 3, 2, 0, 3, 0, 4, 1, 4, 3, 3, 3, 1, 0, 3, 3,
       4, 4, 3, 3, 2, 0, 0, 4, 4, 3, 3, 1, 3, 1, 1, 4, 0, 0, 2, 4, 3, 3,
       2, 3, 3, 0, 1, 1, 1, 3, 3, 3, 3, 1, 1, 1, 0, 4, 3, 3, 3, 3, 4, 4],
      dtype=int32)

In [351]:
model_6 = KMeans(n_clusters=6, random_state=1234, n_init=50, max_iter=30).fit(X=df_q3.loc[:, target_features])
model_6.predict(X=df_q3.loc[:, target_features])

array([2, 4, 4, 3, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 5, 0, 3, 4, 0, 2, 4, 3,
       3, 4, 2, 0, 0, 0, 5, 1, 1, 1, 4, 3, 4, 4, 1, 0, 0, 1, 5, 1, 0, 2,
       1, 0, 2, 4, 0, 3, 2, 1, 4, 1, 5, 0, 1, 4, 0, 1, 5, 4, 2, 4, 4, 4,
       2, 2, 1, 1, 5, 2, 4, 2, 5, 1, 5, 4, 2, 5, 1, 5, 2, 1, 0, 1, 4, 4,
       3, 3, 3, 1, 1, 1, 1, 0, 4, 0, 1, 1, 1, 4, 4, 4, 4, 4, 1, 1, 2, 0,
       1, 4, 4, 2, 4, 2, 1, 4, 4, 4, 4, 4, 1, 1, 2, 4, 4, 1, 3, 3, 4, 2,
       4, 1, 4, 2, 4, 0, 1, 0, 2, 1, 4, 2, 0, 4, 3, 3, 3, 4, 4, 4, 2, 4,
       4, 4, 3, 0, 4, 1, 4, 4, 0, 2, 4, 2, 1, 5, 1, 4, 4, 4, 3, 2, 4, 4,
       1, 1, 4, 4, 0, 2, 5, 1, 1, 4, 4, 3, 4, 3, 3, 1, 2, 5, 0, 1, 4, 4,
       0, 4, 4, 2, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 2, 1, 4, 4, 4, 4, 1, 1],
      dtype=int32)

### 3-5

In [352]:
from sklearn.metrics import silhouette_score

In [353]:
silhouette_score(X=df_q3.loc[:, target_features], labels=model_4.predict(X=df_q3.loc[:, target_features]))

0.4898214650018907

In [354]:
silhouette_score(X=df_q3.loc[:, target_features], labels=model_5.predict(X=df_q3.loc[:, target_features]))

0.5090779061903452

In [355]:
silhouette_score(X=df_q3.loc[:, target_features], labels=model_6.predict(X=df_q3.loc[:, target_features]))

0.5556812882602017

### 3-6

In [358]:
model_5_res = model_5.predict(X=df_q3.loc[:, target_features])

In [359]:
model_6_res = model_6.predict(X=df_q3.loc[:, target_features])

In [366]:
count_5 = [0,0,0,0,0]
for n in model_5_res:
    count_5[n] += 1
count_5

[40, 34, 24, 73, 49]

In [367]:
count_6 = [0,0,0,0,0,0]
for n in model_6_res:
    count_6[n] += 1
count_6

[24, 51, 34, 25, 73, 13]

In [369]:
max(count_5)/min(count_5)

3.0416666666666665

In [370]:
max(count_6)/min(count_6)

5.615384615384615

### Q3 Answer

In [373]:
round((5+ 0.5090779061903452), 2)

5.51