In [1]:
import pandas as pd
import numpy as np

In [2]:
SNS = pd.read_csv('lv2-2504.csv')
SNS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15809 entries, 0 to 15808
Data columns (total 6 columns):
AID           15809 non-null int64
CATEGORY      15809 non-null object
REPUTATION    15809 non-null int64
REPLY         15809 non-null int64
VIEW          15809 non-null int64
UPVOTE        15809 non-null int64
dtypes: int64(5), object(1)
memory usage: 741.2+ KB


# 24

In [3]:
df240 = SNS.copy()

24-1

In [4]:
df240['UP_RATIO'] = df240['UPVOTE']/df240['VIEW']
df240['UP_RATIO'].describe()

count    15809.000000
mean         0.012775
std          0.033149
min          0.000000
25%          0.001411
50%          0.003823
75%          0.010684
max          0.879170
Name: UP_RATIO, dtype: float64

24-2

In [5]:
list_cor = []
for cat in df240['CATEGORY'].unique():
    cor00 = df240.loc[df240['CATEGORY']==cat, ['UP_RATIO','REPUTATION']].corr().iloc[0, 1]
    list_cor.append(cor00)
list_cor

[0.6142020083848924,
 0.6392338476070252,
 0.6523530809223035,
 0.8289612632889164,
 0.6575864492306824,
 0.7548145516773486,
 0.8997604745276688,
 0.8048228459076887,
 0.510050480945406,
 0.4480153846149193]

24-3

In [6]:
res24 = np.max(list_cor) - np.min(list_cor)
ans24 = round(res24, 3)
print(res24)
print('ans24 : ', ans24)

0.45174508991274953
ans24 :  0.452


# 25

In [7]:
df250 = SNS.copy()

25-1

In [8]:
for col in ['REPUTATION','VIEW']:
    max00 = df250[col].max()
    min00 = df250[col].min()
    str00 = col + '_N'
    df250[str00] = 10*(df250[col]-min00)/(max00-min00)

25-2

In [9]:
from sklearn.cluster import KMeans
km00 = KMeans(random_state=1234, n_clusters=4)
km00.fit(df250.loc[:, ['REPUTATION_N','VIEW_N']])
srs00 = pd.Series(km00.labels_)
srs00.index = df250.index
df250['label'] = srs00

25-3

In [10]:
list_cent = []
for lab in range(4):
    cent00 = np.array(df250.loc[df250['label']==lab,['REPUTATION_N','VIEW_N']].mean(axis=0))
    list_cent.append(cent00)

In [11]:
list_cent

[array([0.05995249, 0.08530391]),
 array([4.86909571, 0.16757386]),
 array([0.16989031, 1.71441742]),
 array([1.23841499, 0.09567794])]

25-4

In [12]:
list_dist = []
for i in range(4):
    for j in range(i+1, 4):
        cent00 = list_cent[i]
        cent01 = list_cent[j]
        dist00 = np.sqrt(np.sum((cent00 - cent01)**2))
        list_dist.append(dist00)
list_dist

[4.8098468660133165,
 1.6328187735256652,
 1.1785081657473577,
 4.947247356901718,
 3.6313925002703096,
 1.9396037026681165]

25-5

In [13]:
res25 = np.max(list_dist) - np.min(list_dist)
ans25 = round(res25, 2)
print(res25)
print('ans25 : ', ans25)

3.76873919115436
ans25 :  3.77


# 26

In [14]:
df260 = SNS.copy()

26-1

In [15]:
df261 = df260.copy()
for col in ['REPUTATION','REPLY','VIEW','UPVOTE']:
    q1 = df260[col].quantile(0.25)
    q3 = df260[col].quantile(0.75)
    iqr = q3 - q1
    df261 = df261[(df261[col]>=q1 - 1.5*iqr) & (df261[col]<=q3 + 1.5*iqr)]
df261.shape

(11644, 6)

26-2

In [16]:
df_dum = pd.get_dummies(df261['CATEGORY'], drop_first=True)
list_dum = list(df_dum.columns)
DF6 = pd.concat([df261, df_dum], axis=1)

26-3

In [17]:
train6 = DF6[DF6['AID']%5!=0].copy()
test6 = DF6[DF6['AID']%5==0].copy()
print(train6.shape, test6.shape)

(9331, 15) (2313, 15)


26-4, 26-5

In [18]:
list_fts = ['REPLY','VIEW','UPVOTE'] + list_dum
from sklearn.linear_model import LinearRegression
LR00 = LinearRegression()
LR00.fit(train6.loc[:, list_fts], train6['REPUTATION'])
A6 = np.mean(LR00.predict(test6.loc[:, list_fts]))
res26 = A6
ans26 = round(res26, 3)
print(res26)
print('ans26 : ',ans26)

1836.7031793889687
ans26 :  1836.703


# Summary

In [19]:
print(ans24)
print(ans25)
print(ans26)

0.452
3.77
1836.703
